name: Python application testing

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs:
  run_tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        npm install -g allure-commandline --save-dev
    - name: Set variables depending on a branch
      run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
              export ENV=prod
              echo $ENV
          else
              export ENV=dev
              echo $ENV
          fi
    - name: Test with python
      run: |
        python -m pytest --alluredir=allure-results/ tests/
  
    - name: Deploy test results to EC2 Allure
      if: always()
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        source: "allure-results/*"
       # rm: true
        target: "/var/allure/var/"
